import { Binary } from "@hazae41/binary"

export class PreMasterSecret {

  /**
   * This random value is generated by the client and is used to generate the master secret, as specified in Section 8.1.
   * @param client_version The latest (newest) version supported by the client.  This is used to detect version rollback attacks.
   * @param random 46 securely-generated random bytes.
   */
  constructor(
    readonly client_version: number,
    readonly random: Buffer
  ) { }

  size() {
    return 0
      + 2
      + this.random.length
  }

  write(binary: Binary) {
    binary.writeUint16(this.client_version)
    binary.write(this.random)
  }
}