import { Uint8Array } from "@hazae41/bytes"
import { Cursor } from "@hazae41/cursor"

export class PreMasterSecret {

  /**
   * This random value is generated by the client and is used to generate the master secret, as specified in Section 8.1.
   * @param client_version The latest (newest) version supported by the client.  This is used to detect version rollback attacks.
   * @param random 46 securely-generated random bytes.
   */
  constructor(
    readonly client_version: number,
    readonly random: Uint8Array<46>
  ) { }

  sizeOrThrow() {
    return 2 + this.random.length
  }

  writeOrThrow(cursor: Cursor) {
    cursor.writeUint16OrThrow(this.client_version)
    cursor.writeOrThrow(this.random)
  }

}